export const GoalModalContextState = {
    setFavourite: () => {},
    close: () => {},
    isFavourite: false,
    goalName: '',
    setGoal: () => {},
    descriptionContent: '',
    canAddToFavorite: false,
    setDescription: () => {},
    image: {},
    onButtonClick: () => {},
    deleteAttachement: () => {},
    inputFile: null,
    uploadFile: () => {},
    setDate: () => {},
    dateValue: '',
    missionsData: [],
    setEditCheckbox: () => {},
    setCheckboxes: () => {},
    setDeleteCheckbox: () => {},
    setCommentary: () => {},
    commentaryContent: '',
    sphere: '',
    sphereOnChange: () => {},
    disabledButtonCheck: false,
    setFavouritePatch: () => {},
};
