name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        # key: ${{ secrets.SSH_KEY }}
        # passphrase: ${{ secrets.PASSPHRASE }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd samo_front
          git checkout develop
          git pull origin develop
          npm install
          npm run build
          pm2 restart server.js
